#!/usr/bin/env sh
[ "$HUSKY" = "2" ] && set -x
n=$(basename "$0")
s=$(dirname "$(dirname "$0")")/$n

[ ! -f "$s" ] && exit 0

if [ -f "$HOME/.huskyrc" ]; then
	echo "husky - '~/.huskyrc' is DEPRECATED, please move your code to ~/.config/husky/init.sh"
fi
i="${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh"
[ -f "$i" ] && . "$i"

[ "${HUSKY-}" = "0" ] && exit 0

export PATH="node_modules/.bin:$PATH"
if [ "${OS-}" = "Windows_NT" ] && command -v pwsh >/dev/null 2>&1 && [ -f "$s.win.ps1" ]; then
	pwsh -NoLogo -NoProfile -ExecutionPolicy Bypass -File "$s.win.ps1" "$@"
	c=$?
else
	sh -e "$s" "$@"
	c=$?
fi

[ $c != 0 ] && echo "husky - $n script failed (code $c)"
[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"
exit $c
